// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCev_NV5sTpm9y5LIz3Cz1N_3PujgG_4YM',
    appId: '1:987239272854:web:3f715fee5f5edbdd834db7',
    messagingSenderId: '987239272854',
    projectId: 'loudly-33ac7',
    authDomain: 'loudly-33ac7.firebaseapp.com',
    databaseURL: 'https://loudly-33ac7-default-rtdb.firebaseio.com',
    storageBucket: 'loudly-33ac7.appspot.com',
    measurementId: 'G-EJBYCF2G7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJzIV0D89qhh2jFpRcI6OLepE29V2q510',
    appId: '1:987239272854:android:5c0fbb5d5617ecdf834db7',
    messagingSenderId: '987239272854',
    projectId: 'loudly-33ac7',
    databaseURL: 'https://loudly-33ac7-default-rtdb.firebaseio.com',
    storageBucket: 'loudly-33ac7.appspot.com',
  );
}
